### ISSUE TITLE
It's alive ?

### ISSUE THREAD

**Issue by coreegor** [hunternet93/ddp_asyncio#2]
Is this project alive?
Can you suggest another implementation if not?

**Comment by hunternet93** [comment]
I'm not actively developing ddp_asyncio, but the code should still work just fine. If not, I'll take a look at any issues or PRs that get submitted, though I can't promise to fix anything requiring a large time investment.

I don't have any other implementations to suggest since I haven't worked on any projects using DDP or Meteor for a while now. The protocol's fairly simple though, so extending my implementation or creating a new one wouldn't be terribly difficult.
